# for raw logs format: json or cri (docker|containerd)
container_runtime: containerd
agent:
  persistentVolume:
    enabled: true
    existingClaim: pvc-crowdsec-agent
  # Specify each pod whose logs you want to process
  acquisition:
    # The namespace where the pod is located
    - namespace: traefik
      # The pod name
      podName: traefik-*
      # as in crowdsec configuration, we need to specify the program name to find a matching parser
      program: traefik
  env:
    - name: COLLECTIONS
      value: "crowdsecurity/traefik"
lapi:
  replicas: 2
  type: RollingUpdate
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: run
                  operator: In
                  values:
                    - crowdsec
            topologyKey: kubernetes.io/hostname
          weight: 100
  env:
    # To enroll the Security Engine to the console
    - name: ENROLL_KEY
      valueFrom:
        secretKeyRef:
          name: crowdsec-secrets
          key: crowdsec-enrollment-key
    - name: ENROLL_INSTANCE_NAME
      value: "k8s-prod"
    - name: ENROLL_TAGS
      value: "k8s linux prod"
    - name: BOUNCER_KEY_traefik
      valueFrom:
        secretKeyRef:
          name: crowdsec-secrets
          key: traefik-bouncer-key
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: crowdsec-secrets
          key: crowdsec-db-password
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: crowdsec-secrets
          key: crowdsec-db-username
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 256Mi
      cpu: 100m
  persistentVolume:
    config:
      enabled: true
      existingClaim: pvc-crowdsec-config
    data:
      enabled: true
      existingClaim: pvc-crowdsec-data
## config.yaml.local is the configuration file used by the Security Engine itself
config:
  config.yaml.local: |
    api:
      client:
        # the log processor will remove delete itself from LAPI when stopping.    
        unregister_on_exit: true
      server:
        # This is needed for agent autoregistration
        auto_registration: # Activate if not using TLS for authentication
          enabled: true
          token: "${REGISTRATION_TOKEN}" # /!\ Do not modify this variable (auto-generated and handled by the chart)
          allowed_ranges: # /!\ Make sure to adapt to the pod IP ranges used by your cluster
            - "127.0.0.1/32"
            - "10.0.0.4/16"
            - "10.0.0.0/8"
    db_config:
      type: postgresql
      user: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      db_name: crowdsec
      host: crowdsec-db-postgresql.crowdsec.svc.cluster.local
      port: 5432
      flush:
        bouncers_autodelete:
          api_key: 1h
appsec:
  enabled: true
  replicas: 2
  type: RollingUpdate
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: run
                  operator: In
                  values:
                    - crowdsec
            topologyKey: kubernetes.io/hostname
          weight: 100
  acquisitions:
    - source: appsec
      listen_addr: "0.0.0.0:7422"
      path: /
      appsec_configs:
        - crowdsecurity/appsec-default
        #- crowdsecurity/crs
      labels:
        type: appsec
  env:
    - name: COLLECTIONS
      value: "crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-crs crowdsecurity/appsec-generic-rules"
