---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cluster-role.yaml
- deployment.yaml
- ingress.yaml
- secret.yaml
- service.yaml
- service-account.yaml
- pv-config.yaml
- pvc-config.yaml
