apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-homepage-config
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/nfs/storage/homepage"
    server: "10.0.0.4"
    readOnly: false
