apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-homepage-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: ""
  volumeName: pv-homepage-config
