---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-production

spec:
  destination:
    namespace: argocd
    name: production
  project: default
  source:
    path: argocd-apps
    repoURL: https://github.com/mimotej/kubernetes-homelab-mirror.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - Validate=false
      - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      allowEmpty: true
