---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

helmCharts:
  - name: descheduler
    includeCRDs: true
    version: 0.36.0
    repo: https://kubernetes-sigs.github.io/descheduler
    valuesFile: overlays/values.yaml
    namespace: kube-system
    releaseName: descheduler


