---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

helmCharts:
  - name: cilium
    includeCRDs: true
    version: 1.19.5
    repo: oci://quay.io/cilium/charts
    namespace: kube-system
    releaseName: cilium
    valuesFile: overlays/values.yaml
