---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gotify-default-user
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
  - secretKey: password
    remoteRef:
      key: "gotify-password"


