---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: librechat-credentials-env
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: CREDS_KEY
      remoteRef:
        key: "librechat-creds"
    - secretKey: JWT_SECRET
      remoteRef:
        key: "librechat-jwt"
    - secretKey: JWT_REFRESH_SECRET
      remoteRef:
        key: "librechat-refresh-jwt"
    - secretKey: MEILI_MASTER_KEY
      remoteRef:
        key: "librechat-meili"
