---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
spec:
  destination:
    namespace: external-secrets
    name: production
  project: default
  source:
    path: apps/external-secrets-operator
    repoURL: https://github.com/mimotej/kubernetes-homelab-mirror.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - Validate=false
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
    automated:
      prune: true
      allowEmpty: true
