---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crowdsec

resources:
- ../../cluster/base/namespaces/crowdsec
- base

helmCharts:
  - name: crowdsec
    includeCRDs: true
    repo: https://crowdsecurity.github.io/helm-charts
    version: 0.24.0
    valuesFile: overlays/values.yaml
    namespace: crowdsec
    releaseName: crowdsec
  - name: postgresql
    repo: https://charts.bitnami.com/bitnami
    valuesFile: overlays/values-db.yaml
    version: 18.7.3
    namespace: crowdsec
    releaseName: crowdsec-db

