---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- ingressRoute.yaml
- service.yaml
- pv-docker-data.yaml
- pv-storage-media.yaml
- pvc-docker-data.yaml
- pvc-storage-media.yaml
