---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-postgres-external-secret
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
  - secretKey: username
    remoteRef:
      key: "authentik-postgres-username"
  - secretKey: password
    remoteRef:
      key: "authentik-postgres-password"



