apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-authentik
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/nfs/storage/authentik-kubernetes/data"
    server: "10.0.0.4"
    readOnly: false
