apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-authentik
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  volumeName: pv-authentik
