apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-authentik-brand
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: ""
  volumeName: pv-authentik-brand
