---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: adguard-home

resources:
- ../../cluster/base/namespaces/adguard-home
- base

helmCharts:
  - name: adguard-home
    valuesFile: overlays/values.yaml
    includeCRDs: true
    version: 13.6.0
    repo: oci://oci.trueforge.org/truecharts
    namespace: adguard-home
    releaseName: adguard-home

