apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jellyfin-tv
spec:
  capacity:
    storage: 1700Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /storage/media/jellyfin/tv_series
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: platform
          operator: In
          values:
          - n100


