apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jellyfin-tv
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1700Gi
  storageClassName: local-storage
  volumeName: pv-jellyfin-tv

