apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jellyfin-media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1700Gi
  storageClassName: local-storage
  volumeName: pv-jellyfin-media

