---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - certificate.yaml
  - clusterRoleBinding.yaml
  - ingress.yaml
  - ingress-secure.yaml
  - external-secret.yaml
  - middleware-headers.yaml
  - secret.yaml
