---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich

resources:
- ../../cluster/base/namespaces/immich
- base

helmCharts:
  - name: immich
    valuesFile: overlays/values.yaml
    includeCRDs: true
    version: 0.12.0
    repo: oci://ghcr.io/immich-app/immich-charts
    namespace: immich
    releaseName: immich
  - name: postgresql
    repo: https://charts.bitnami.com/bitnami
    valuesFile: overlays/values-db.yaml
    version: 18.6.8
    namespace: immich
    releaseName: immich-db


