---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-secrets
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: admin-username
      remoteRef:
        key: "nextcloud-admin-username"
    - secretKey: admin-password
      remoteRef:
        key: "nextcloud-admin-password"
    - secretKey: smtp-username
      remoteRef:
        key: "nextcloud-smtp-username"
    - secretKey: smtp-password
      remoteRef:
        key: "nextcloud-smtp-password"
    - secretKey: smtp-host
      remoteRef:
        key: "nextcloud-smtp-host"
    - secretKey: db-username
      remoteRef:
        key: "nextcloud-db-username"
    - secretKey: db-password
      remoteRef:
        key: "nextcloud-db-password"
    - secretKey: db-host
      remoteRef:
        key: "nextcloud-db-host"
    - secretKey: db-name
      remoteRef:
        key: "nextcloud-db-name"
    - secretKey: redis-password
      remoteRef:
        key: "nextcloud-redis-password"
