apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nextcloud-redis
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /nfs/storage/nextcloud/redis
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: platform
              operator: In
              values:
                - n100
