apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nextcloud-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  volumeName: pv-nextcloud-data
