apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: seerr-chart
spec:
  template:
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 10.0.0.15      # Custom DNS server

