apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-zerobyte-docker-data
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/nfs/storage"
    server: "10.0.0.4"
    readOnly: true
