---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: adguard

spec:
  entryPoints:
    - web
  routes:
    - match: Host(`adguard.internal`)
      kind: Rule
      services:
        - name: adguard-home
          port: 4080


