---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- externalSecret.yaml
- pv-additional-data.yaml
- pv-terraform-states.yaml
- pvc-additional-data.yaml
- pvc-terraform-states.yaml
