apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-arc-portainer-terraform-states
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/nfs/storage/terraform-states"
    server: "10.0.0.4"
    readOnly: false
