---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  destination:
    namespace: argocd
    name: production
  project: default
  source:
    path: apps/argocd
    repoURL: https://github.com/mimotej/kubernetes-homelab-mirror.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - Validate=false
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
    automated:
      prune: true
      allowEmpty: true
