---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: traefik-middleware-auth
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
  - secretKey: authentik-traefik-client-id
    remoteRef:
      key: "authentik-traefik-client-id"
  - secretKey: authentik-traefik-client-secret
    remoteRef:
      key: "authentik-traefik-client-secret"
  - secretKey: traefik-plugin-oidc-secret
    remoteRef:
      key: "traefik-plugin-oidc-secret"

