---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crowdsec-secrets
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
  - secretKey: crowdsec-db-username
    remoteRef:
      key: "crowdsec-db-username"
  - secretKey: crowdsec-db-password
    remoteRef:
      key: "crowdsec-db-password"
  - secretKey: crowdsec-enrollment-key
    remoteRef:
      key: "crowdsec-enrollment-key"
  - secretKey: traefik-bouncer-key
    remoteRef:
      key: "traefik-bouncer-key"

