apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-crowdsec-agent
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nfs/storage/crowdsec-k8s/crowdsec-agent
    server: "10.0.0.4"
    readOnly: false
