apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-crowdsec-db-dump
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/nfs/storage/crowdsec-k8s/db_dump"
    server: "10.0.0.4"
    readOnly: false
