apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-crowdsec-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  volumeName: pv-crowdsec-data

