---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "homeassistant.fullname" . }}
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    rollingUpdate: null
    type: Recreate
  selector:
    matchLabels:
      {{- include "homeassistant.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "homeassistant.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      hostNetwork: {{ .Values.hostNetwork.enabled | default false }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository | default "ghcr.io/home-assistant/home-assistant" }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: homeassistant
              containerPort: {{ .Values.service.port | default 8123 }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /config
              name: {{ include "homeassistant.fullname" . }}-config-pvc
            {{- if .Values.backups.enabled }}
            - mountPath: /config/backups
              name: {{ include "homeassistant.fullname" . }}-backups-pvc
            {{- end }}
            - mountPath: /run/dbus
              name: dbus-socket
              readOnly: true
            - mountPath: /etc/localtime
              name: localtime
              readOnly: true
        {{- if .Values.matter.enabled }}
        - name: matter-{{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.matter.image.repository | default "ghcr.io/home-assistant-libs/python-matter-server" }}:{{ .Values.matter.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.matter.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: matter
              containerPort: {{ .Values.matter.port | default 5580 }}
              protocol: TCP
          {{- with .Values.matter.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /data
              name: {{ include "homeassistant.fullname" . }}-matter-pvc
            - mountPath: /run/dbus
              name: dbus-socket
              readOnly: true
        {{- end }}
      volumes:
          - name: dbus-socket
            hostPath: 
              path: /run/dbus
          - name: localtime
            hostPath:
              path: /etc/localtime
        {{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
          - name: {{ include "homeassistant.fullname" . }}-config-pvc
            persistentVolumeClaim:
              claimName: {{ include "homeassistant.fullname" . }}-config-pvc
        {{- else if .Values.persistence.enabled }}
          - name: {{ include "homeassistant.fullname" . }}-config-pvc
            persistentVolumeClaim:
              claimName: {{ .Values.persistence.existingClaim }}
        {{- else }}
          - name: config
            emptyDir: {}
        {{- end }}
        {{- if and .Values.backups.enabled (not .Values.backups.existingClaim) }}
          - name: {{ include "homeassistant.fullname" . }}-backups-pvc
            persistentVolumeClaim:
              claimName: {{ include "homeassistant.fullname" . }}-backups-pvc
        {{- else if .Values.backups.enabled }}
          - name: {{ include "homeassistant.fullname" . }}-backups-pvc
            persistentVolumeClaim:
              claimName: {{ .Values.backups.existingClaim }}
        {{- else  }}
          - name: backups
            emptyDir: {}
        {{- end }}
        {{- if and .Values.matter.persistence.enabled (not .Values.matter.persistence.existingClaim) }}
          - name: {{ include "homeassistant.fullname" . }}-matter-pvc
            persistentVolumeClaim:
              claimName: {{ include "homeassistant.fullname" . }}-matter-pvc
        {{- else if .Values.matter.persistence.enabled }}
          - name: {{ include "homeassistant.fullname" . }}-matter-pvc
            persistentVolumeClaim:
              claimName: {{ .Values.matter.persistence.existingClaim }}
        {{- else  }}
          - name: matter
            emptyDir: {}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

