{{- if .Values.ingress.enabled -}}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "homeassistant.fullname" . }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      services:
        - name: {{ include "homeassistant.fullname" . }}
          port: {{ .Values.service.port | default 8123 }}
{{- end }}
