---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "homeassistant.fullname" . }}
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port | default 8123 }}
      targetPort: {{ .Values.service.port | default 8123 }}
      protocol: TCP
      name: homeassistant
  selector:
    {{- include "homeassistant.selectorLabels" . | nindent 4 }}
{{- if .Values.service.loadBalancer.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "homeassistant.fullname" . }}-lb
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.port | default 8123 }}
      targetPort: {{ .Values.service.port | default 8123 }}
      protocol: TCP
  selector:
    {{- include "homeassistant.selectorLabels" . | nindent 4 }}
{{- end }}
