apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres-immich
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 60Gi
  storageClassName: local-storage
  volumeName: pv-postgres-immich

