apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-immich-library
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 800Gi
  storageClassName: local-storage
  volumeName: pv-immich-library

