---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wg-easy-secrets
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
  - secretKey: username
    remoteRef:
      key: "wg-easy-username"
  - secretKey: password
    remoteRef:
      key: "wg-easy-password"


