---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: onlyoffice-secrets
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: onlyoffice-db-username
      remoteRef:
        key: "onlyoffice-db-username"
    - secretKey: onlyoffice-db-password
      remoteRef:
        key: "onlyoffice-db-password"
    - secretKey: onlyoffice-rabbitmq-secret
      remoteRef:
        key: "onlyoffice-rabbitmq-secret"
    - secretKey: onlyoffice-redis-secret
      remoteRef:
        key: "onlyoffice-redis-secret"
    - secretKey: onlyoffice-amqp-connection-string
      remoteRef:
        key: "onlyoffice-amqp-connection-string"
    - secretKey: onlyoffice-jwt-secret
      remoteRef:
        key: "onlyoffice-jwt-secret"
