apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-onlyoffice-db-dump
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/nfs/storage/onlyoffice/db_dump"
    server: "10.0.0.4"
    readOnly: false
