apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-auth-token
spec:
  refreshInterval: "30m0s"
  target:
    name: renovate-secret
    template:
      type: Opaque
      engineVersion: v2
      data:
        GITHUB_COM_TOKEN:  "{{ .token }}"
        GITHUB_COM_USER: bWltb3Rlai1ob21lbGFiLWJvdA==
        RENOVATE_TOKEN: "{{ .token }}"
        # add additional fields you need, you can specify multiple sources in dataFrom to template more values in here
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: GithubAccessToken
          name: github-auth-token
