apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: renovate-github
  namespace: renovate-operator
spec:
  discoveryFilters: ["mimotej/kubernetes-homelab-mirror*"]
  provider:
    name: github
  image: renovate/renovate:43.190.1
  parallelism: 5
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  schedule: 14 1 * * *
  secretRef: renovate-secret
