---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - ../../cluster/base/namespaces/argocd
  - base
  - https://raw.githubusercontent.com/argoproj/argo-cd/v3.4.2/manifests/install.yaml

patches:
  - path: overlays/argocd-cmd-params-cm.yaml
  - path: overlays/argocd-cm.yaml
  - path: overlays/argocd-rbac-cm.yaml

# images:
#   - name: quay.io/argoproj/argocd
#     newName: ghcr.io/argoproj/argo-cd/argocd
#     newTag: v3.4.2
